- name: CFtest create project and user in openstack
  hosts: localhost
  gather_facts: false
  vars:
    cloud_admin: admin
    admin_password: Passw0rd
    admin_project: admin
    os_auth: https://openstack.home.lab:13000/v2.0
    project_name: CFtest
    project_password: Passw0rd

  tasks:


  -  name: delete users
     os_user:
       auth:
         auth_url: "{{ os_auth }}"
         username: "{{ cloud_admin }}"
         password: "{{ admin_password }}"
         project_name: "{{ admin_project }}"
       state: absent
       name: "{{ project_name }}"
       password: "{{ project_password }}"
       domain: "{{ project_name }}"
       default_project: "{{ project_name }}"
       validate_certs: False
       endpoint_type: admin


  -  name: delete projects  
     os_project:
       auth:
         auth_url: "{{ os_auth }}"
         username: "{{ cloud_admin }}"
         password: "{{ admin_password }}"
         project_name: "{{ admin_project }}"

       state: absent
       enabled: True
       name: "{{ project_name }}"
       validate_certs: False
       endpoint_type: admin
